title: "今日から使える！OSSプルリク集 #megurorb"
author: "sue445"
#theme: "sky"

meta_properties:
  og:locale: "ja_JP"
  og:type: "website"
  og:title: "今日から使える！OSSプルリク集 #megurorb"
  og:description: "Meguro.rb#2 2017/04/20(Thu) の発表資料です"
  og:url: "https://sue445.github.io/megurorb-02/#/"
  og:image: "https://sue445.github.io/megurorb-02/images/cure_custard.jpg"

meta_names:
  twitter:card: "Summary"
  twitter:site: "@sue445"
  twitter:creator: "@sue445"
  twitter:title: "今日から使える！OSSプルリク集 #megurorb"
  twitter:description: "Meguro.rb#2 2017/04/20(Thu) の発表資料です"
  twitter:image: "https://sue445.github.io/megurorb-02/images/cure_custard.jpg"
